# Generated by Django 4.2.13 on 2026-09-18 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_enrolled', models.BooleanField(default=False, help_text='True once face samples have been captured AND the model retrained.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('time_in', models.TimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(help_text='KNN confidence score at time of marking (0-1)')),
                ('method', models.CharField(default='face_recognition', help_text='How attendance was captured, e.g. face_recognition / manual', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.student')),
            ],
            options={
                'ordering': ['-date', '-time_in'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
